version: '3'

services:
  api:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapi
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - .docker/db:/data/db

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
